### ISSUE TITLE
[Bug] 对Llama-3-70B-Instruct进行量化的时候会出现OOM的问题

### ISSUE THREAD

**Issue by ZGW99** [InternLM/lmdeploy#1796]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

以上是错误信息，看起来是此表越界，但是我调试之后发现其中的参数输出和llama-3-8B（成功运行）是一致的。
最后发现我调整--calib-samples 128 --calib-seqlen 2048 两个参数的值为1时，模型进行成功量化，所以猜测是显存不够用，所以保证两个参数的值在可用范围内怎么进行量化，能不能多卡量化共享显存

### Reproduction

 lmdeploy lite auto_awq Meta-Llama-3-70B-Instruct --work-dir ./Meta-Llama-3-70B-Instruct-4bit

### Environment

```Shell
Python: 3.8.16
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
NVIDIA A100 80GB
TorchVision: 0.17.2+cu121
LMDeploy: 0.4.2+
transformers: 4.40.0
gradio: 3.50.2
fastapi: 0.111.0
pydantic: 2.7.1
triton: 2.2.0
```

**Comment by AllentDan** [comment]
应该不会占用这么多，我量化 llama3-70b 的 llava 才用了20GB。你在 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/lite/apis/calibrate.py#L183 下面插一句`model.config.use_cache = False` 试试。因为之前的版本处理一般 LLM 时候，会自动考虑离线量化，会有比较大的 kv_cache 的开销。

**Comment by ZGW99** [comment]
`   if model_type == 'llm':
        # Load tokenizer and configuration
        tokenizer = AutoTokenizer.from_pretrained(model,
                                                  use_fast=True, # 此处修改，原值为False
                                                  legacy=False, # 新增
                                                  trust_remote_code=True)

        model = load_hf_from_pretrained(model,
                                        torch_dtype=torch.float16,
                                        trust_remote_code=True)
        vl_model = None
    elif model_type == 'vlm':
        from lmdeploy.vl.model.builder import vl_model_with_tokenizer
        vl_model, model, tokenizer = vl_model_with_tokenizer(model_path=model)

    model_type = type(model).__name__
    # 新增
    model.config.use_cache = False`
感谢回答，我按照你的回复增加了model.config.use_cache = False，错误没有变化，还是会有上述错误。
有两个前提：
1.代理问题量化的模型是在本地
2.我还修改了calibrate.py文件的两处内容，代码如上
我是个新手不知道上面的改动是不是有影响

**Comment by AllentDan** [comment]
量化模型在本地不影响，不需要修改源代码。另外我之前没看仔细，你这也没 OOM，感觉像是环境没配置好。可以正常用 transformers 跑70b模型的 demo 吗？

**Comment by ZGW99** [comment]
可以正常跑，但是单卡也是跑不起来，用8卡跑起来的。使用lmdeploy的8卡也可以跑起来，同环境llama-8b也是没问题可以正常跑，正常量化。70B设置参数--calib-seqlen 1 --calib-samples 1之后就没有这个错误，可以进入量化过程了

**Comment by AllentDan** [comment]
复现不出来错误，默认参数启动。

**Comment by lg123666** [comment]
> 化过程了

请问llama3 70b模型量化成功了吗？输出结果正常吗？

**Comment by ZGW99** [comment]
还是不行，找不到问题，有思路吗

**Comment by lg123666** [comment]
> 还是不行，找不到问题，有思路吗

我之前可以正常量化，但是量化模型输出结果不正常
https://github.com/InternLM/lmdeploy/issues/1562

**Comment by ZGW99** [comment]
是不是校准数据集调的太小了，还是量化失败了输出乱码，用的什么卡

**Comment by lg123666** [comment]
> 是不是校准数据集调的太小了，还是量化失败了输出乱码，用的什么卡

用的lmdeploy提供的方式，唯一修改的就是把calib-seqlen改成了1024。3090卡

**Comment by ZGW99** [comment]
能辛苦看一下你的环境吗，感谢，lmdeploy check_env

**Comment by lg123666** [comment]
> 能辛苦看一下你的环境吗，感谢，lmdeploy check_env

https://github.com/InternLM/lmdeploy/issues/1562

**Comment by ZGW99** [comment]
> 复现不出来错误，默认参数启动。

好的感谢，我的模型时modelscope下载的，和模型下载源会有关系吗

**Comment by AllentDan** [comment]
按理不会，可能是环境问题。错误复现不出来
