### ISSUE TITLE
[Bug] docker src build后运行lmdeploy.pipe报错ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zhiwei35** [InternLM/lmdeploy#2128]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

1.参考`https://github.com/InternLM/lmdeploy/blob/v0.5.1/docs/en/build.md #build in docker`部分一步步做的，最后`pip install lmdeploy-0.5.1-cp310-cp310-manylinux2014_x86_64.whl`
2.`nvidia-smi`显示cuda和驱动版本为Driver Version: 550.90.07，CUDA Version: 12.4 
3.错误：`ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory`

### Reproduction

1.错误出现截图
![image](https://github.com/user-attachments/assets/249d67f9-8514-4441-bab7-0b9c4ed90862)
2.尝试过的解决办法: `export LD_LIBRARY_PATH=/path/to/libcudart.so.11.0:$LD_LIBRARY_PATH`，仍然报同样的错误

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

LMDeploy: 0.2.0+b319dce
transformers: 4.43.1
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
```

**Comment by Zhiwei35** [comment]
若能帮助解决，不胜感激~

**Comment by Zhiwei35** [comment]
试了一下拉取cuda12.2和12.4的镜像下来，但是没有找到...
<img width="659" alt="image" src="https://github.com/user-attachments/assets/c39f19c6-de9b-4feb-b226-ebe244d1a5fa">

**Comment by Zhiwei35** [comment]
@lvhan028 有空时能麻烦帮我看看不？非常感谢~

**Comment by lvhan028** [comment]
openmmlab/lmdeploy-builder 镜像是用来编译 whl 包并发布pypi package的。不是用来运行的。

用来运行的镜像是 openmmlab/lmdeploy。如果是来做实验的话，也可以直接在openmmlab/lmdeploy中编译。
用脚本 generate.sh，然后 make -j$(nproc) && make install

**Comment by Zhiwei35** [comment]
@lvhan028 感谢答复，我下去后试了一下，已经成功make install
![image](https://github.com/user-attachments/assets/663be461-4ba4-4f5a-9496-f94d60c40a07)
但是我运行./bin/llama_triton_example发现未zhao找到llama_config.ini
![image](https://github.com/user-attachments/assets/d39739ff-6f8a-4a6e-b69a-d78e66130c5c)
并且llama_config.ini的L6的model_dir我也没有，请问我是不是只需要把根目录下的examples/llama/llama_config.ini拿过来就好了，那么这个model_dir所示的模型格式，是要经过一些脚本得到嘛？
![image](https://github.com/user-attachments/assets/517e1cae-a8be-49ea-8acb-04fbbccaf3dc)
感谢解答，麻烦了

**Comment by lvhan028** [comment]
llama_triton_example废弃不用了。
我们用python接口。入 README 文档所示。

**Comment by Zhiwei35** [comment]
get，我再试试，感谢

**Comment by lvhan028** [comment]
可以多加几行日志，debug看看
