### ISSUE TITLE
[Bug] CUDA runtime error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by thiner** [InternLM/lmdeploy#2195]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Not able to serve Qwen2-72b-instruct-awq model, LMDeploy creashes when query the `/chat/completion` API.

### Reproduction

`lmdeploy serve api_server --model-format awq --quant-policy 4 --tp 4 --rope-scaling-factor 2.0 --cache-max-entry-count 0.1`
I have tried remove `--rope-scaling-factor` and `--cache-max-entry-count`, the error remains. 

### Environment

```Shell
lmdeploy check_env
sys.platform: linux
Python: 3.8.10 (default, Mar 25 2024, 10:42:49) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A10
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden-DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor-Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.0+cu118
LMDeploy: 0.5.2.post1+
transformers: 4.43.2
gradio: 4.39.0
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.1.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     SYS     SYS     32-63,96-127    1               N/A
GPU1    PIX      X      SYS     SYS     32-63,96-127    1               N/A
GPU2    SYS     SYS      X      PIX     32-63,96-127    1               N/A
GPU3    SYS     SYS     PIX      X      32-63,96-127    1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
[TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 20, max_q = 20, max_k = 20

 terminate called after throwing an instance of 'std::runtime_error'

 terminate called recursively

   what():  [TM][ERROR] CUDA runtime error: an illegal memory access was encountered /opt/lmdeploy/src/turbomind/utils/allocator.h:233 

 terminate called recursively
```

**Comment by heibaidaolx123** [comment]
same error when serving internvl2-40B using official docker image v0.5.2

**Comment by lzhangzz** [comment]
@thiner Is the problem still exists if `--quant-policy 4` is removed?

Can you repreduce it with environment variable `TM_DEBUG_LEVEL=DEBUG`? (or better, use `compute-sanitizer`)

**Comment by thiner** [comment]
No luck.
```
INFO:     Started server process [1]

 INFO:     Waiting for application startup.

 INFO:     Application startup complete.

 INFO:     Uvicorn running on http://0.0.0.0:3333 (Press CTRL+C to quit)

 2024-07-31 15:06:36,187 - lmdeploy - INFO - prompt='<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nping<|im_end|>\n<|im_start|>assistant\n', gen_config=EngineGenerationConfig(n=1, max_new_tokens=5, top_p=1.0, top_k=40, temperature=0.7, repetition_penalty=1.0, ignore_eos=False, random_seed=6073586891962856184, stop_words=[151645], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 9989, 151645, 198, 151644, 77091, 198], adapter_name=None.

 2024-07-31 15:06:36,187 - lmdeploy - INFO - session_id=1, history_tokens=0, input_tokens=20, max_new_tokens=5, seq_start=True, seq_end=True, step=0, prep=True

 2024-07-31 15:06:36,187 - lmdeploy - INFO - Register stream callback for 1

 [TM][INFO] [forward][rank=0] INPUT: STOP [1]

 [TM][INFO] [forward][rank=0] INPUT: random_seed [1]

 [TM][INFO] [forward][rank=0] INPUT: input_ids [1, 20]

 [TM][INFO] [forward][rank=0] INPUT: input_lengths [1]

 [TM][INFO] [forward][rank=0] INPUT: CORRID [1]

 [TM][INFO] [forward][rank=0] INPUT: request_output_len [1]

 [TM][INFO] [forward][rank=0] INPUT: runtime_top_k [1]

 [TM][INFO] [forward][rank=0] INPUT: runtime_top_p [1]

 [TM][INFO] [forward][rank=0] INPUT: END [1]

 [TM][INFO] [forward][rank=0] INPUT: temperature [1]

 [TM][INFO] [forward][rank=0] INPUT: repetition_penalty [1]

 [TM][INFO] [forward][rank=0] INPUT: stop_words_list [1, 2, 1]

 [TM][INFO] [forward][rank=0] INPUT: step [1]

 [TM][INFO] [forward][rank=0] INPUT: START [1]

 [TM][INFO] [forward][rank=0] OUTPUT: sequence_length [1, 1]

 [TM][INFO] [forward][rank=0] OUTPUT: output_ids [1, 1, 32776]

 [TM][INFO] [forward] Enqueue requests

 [TM][INFO] [forward] Wait for requests to complete ...

 [TM][INFO] [ProcessInferRequests] Request for 1 received.

 [TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 20, max_q = 20, max_k = 20

 terminate called after throwing an instance of 'std::runtime_error'

 terminate called recursively

 terminate called recursively

   what():  [TM][ERROR] CUDA runtime error: an illegal memory access was encountered /opt/lmdeploy/src/turbomind/models/llama/unified_attention_layer.cc:326 

 

 terminate called recursively

 [qwen2-72b-857bd98774-tltmn:1    :0:234] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
```

**Comment by thiner** [comment]
what a surprise! It's working if fallback to `LMDeploy-v0.5.0`. All the arguments remain the same, just changed the LMDeploy version number.

```
INFO:     Started server process [1]

 INFO:     Waiting for application startup.

 INFO:     Application startup complete.

 INFO:     Uvicorn running on http://0.0.0.0:3333 (Press CTRL+C to quit)

 2024-07-31 15:47:53,434 - lmdeploy - INFO - prompt='<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nping<|im_end|>\n<|im_start|>assistant\n', gen_config=EngineGenerationConfig(n=1, max_new_tokens=5, top_p=1.0, top_k=40, temperature=0.7, repetition_penalty=1.0, ignore_eos=False, random_seed=11602628458385238215, stop_words=[151645], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 9989, 151645, 198, 151644, 77091, 198], adapter_name=None.

 2024-07-31 15:47:53,434 - lmdeploy - INFO - session_id=1, history_tokens=0, input_tokens=20, max_new_tokens=5, seq_start=True, seq_end=True, step=0, prep=True

 2024-07-31 15:47:53,434 - lmdeploy - INFO - Register stream callback for 1

 [TM][INFO] [forward][rank=0] INPUT: STOP [1]

 [TM][INFO] [forward][rank=0] INPUT: random_seed [1]

 [TM][INFO] [forward][rank=0] INPUT: input_ids [1, 20]

 [TM][INFO] [forward][rank=0] INPUT: input_lengths [1]

 [TM][INFO] [forward][rank=0] INPUT: CORRID [1]

 [TM][INFO] [forward][rank=0] INPUT: request_output_len [1]

 [TM][INFO] [forward][rank=0] INPUT: runtime_top_k [1]

 [TM][INFO] [forward][rank=0] INPUT: runtime_top_p [1]

 [TM][INFO] [forward][rank=0] INPUT: END [1]

 [TM][INFO] [forward][rank=0] INPUT: temperature [1]

 [TM][INFO] [forward][rank=0] INPUT: repetition_penalty [1]

 [TM][INFO] [forward][rank=0] INPUT: stop_words_list [1, 2, 1]

 [TM][INFO] [forward][rank=0] INPUT: step [1]

 [TM][INFO] [forward][rank=0] INPUT: START [1]

 [TM][INFO] [forward][rank=0] OUTPUT: sequence_length [1, 1]

 [TM][INFO] [forward][rank=0] OUTPUT: output_ids [1, 1, 32776]

 [TM][INFO] [forward] Enqueue requests

 [TM][INFO] [forward] Wait for requests to complete ...

 [TM][INFO] [ProcessInferRequests] Request for 1 received.

 [TM][INFO] [initializeSampling] stop_words_list [1, 2, 1]

 [TM][INFO] [initializeSampling] runtime_top_k [1]

 [TM][INFO] [initializeSampling] runtime_top_p [1]

 [TM][INFO] [initializeSampling] temperature [1]

 [TM][INFO] [initializeSampling] repetition_penalty [1]

 [TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 20, max_q = 20, max_k = 20

 [TM][INFO] [Forward] step = 19, [    47]

 [TM][INFO] [Finish] slot 0, tokens [ 151644 8948 198 2610 525 264 10950 17847 13 151645 198 151644 872 198 9989 151645 198 151644 77091 198 47]

 [TM][INFO] ------------------------- step = 20 -------------------------

 [TM][INFO] [Forward] step = 20, [   644]

 [TM][INFO] [Finish] slot 0, tokens [ 151644 8948 198 2610 525 264 10950 17847 13 151645 198 151644 872 198 9989 151645 198 151644 77091 198 47 644]

 [TM][INFO] [Forward] step = 21, [     0]

 [TM][INFO] [Finish] slot 0, tokens [ 151644 8948 198 2610 525 264 10950 17847 13 151645 198 151644 872 198 9989 151645 198 151644 77091 198 47 644 0]

 [TM][INFO] [Forward] step = 22, [151645]

 [TM][INFO] [Finish] slot 0, tokens [ 151644 8948 198 2610 525 264 10950 17847 13 151645 198 151644 872 198 9989 151645 198 151644 77091 198 47 644 0 151645]

 [TM][INFO] [Interrupt] slot = 0, id = 1

 [TM][INFO] [Interrupt] slot 0, tokens [ 151644 8948 198 2610 525 264 10950 17847 13 151645 198 151644 872 198 9989 151645 198 151644 77091 198 47 644 0 151645]

 [TM][INFO] [forward] Request completed for 1

 2024-07-31 15:47:53,727 - lmdeploy - INFO - UN-register stream callback for 1

 INFO:     10.70.2.27:46064 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by lzhangzz** [comment]
Thanks for the information. 

Could you please help to check if v0.5.1 works for you? My speculation is that it's caused by #2082 on a system without NVLink. However I don't have access to system like yours.

**Comment by thiner** [comment]
@lzhangzz I need to repack the image as mentioned above, can't do it at home. I shall try v0.5.1 tomorrow. Meanwhile, I found a warning which is strange:
```
 [TM][WARNING] [ProcessInferRequests] [21] total sequence length (695 + 59305) exceeds `session_len` (8000), `request_output_len` is truncated to 7304
```
I have set the argument `--rope-scaling-factor 2.0 --session-len 60000`. Is this a bug?

**Comment by thiner** [comment]
> @lzhangzz I need to repack the image as mentioned above, can't do it at home. I shall try v0.5.1 tomorrow. Meanwhile, I found a warning which is strange:
> 
> ```
>  [TM][WARNING] [ProcessInferRequests] [21] total sequence length (695 + 59305) exceeds `session_len` (8000), `request_output_len` is truncated to 7304
> ```
> 
> I have set the argument `--rope-scaling-factor 2.0 --session-len 60000`. Is this a bug?

Problem solved by adding `--quant-policy 4` to the cli start-up arguments.

**Comment by thiner** [comment]
> Thanks for the information.
> 
> Could you please help to check if v0.5.1 works for you? My speculation is that it's caused by #2082 on a system without NVLink. However I don't have access to system like yours.

Tested on v0.5.1 with same arguments, working like a charm!

**Comment by edwardzjl** [comment]
I'm deploying OpenGVLab/InternVL2-26B with lmdeploy and encountered the same issue.
0.5.1 works, 0.5.2+ not.

**Comment by lvhan028** [comment]
#2218 is addressing this issue. Stay tuned.

**Comment by lzhangzz** [comment]
@thiner @edwardzjl 

We have created pre-built packages from #2218 accessable from the following link. Could you please help to verify if the problem is solved on your system?

https://github.com/irexyc/lmdeploy/releases/tag/v0.0.4

**Comment by thiner** [comment]
Seems not working.
```
 [TM][INFO] [forward] Enqueue requests

 [TM][INFO] [forward] Wait for requests to complete ...

 [TM][INFO] [ProcessInferRequests] Request for 1 received.

 [TM][WARNING] [ProcessInferRequests] [1] total sequence length (679 + 59321) exceeds `session_len` (60000), `request_output_len` is truncated to 59320

 [TM][INFO] [Forward] [0, 1), dc=0, pf=1, sum_q=679, sum_k=679, max_q=679, max_k=679

 terminate called after throwing an instance of 'std::runtime_error'

   what():  [TM][ERROR] CUDA runtime error: an illegal memory access was encountered /lmdeploy/src/turbomind/models/llama/LlamaBatch.h:143 

 

 terminate called recursively

 [qwen2-72b-65bd844c9d-hxb7p:1    :0:289] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))

 terminate called recursively

 terminate called recursively
```
`lmdeploy check_env`:
```
root@qwen2-72b-65bd844c9d-hxb7p:/app# lmdeploy check_env
sys.platform: linux
Python: 3.8.10 (default, Mar 25 2024, 10:42:49) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A10
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.0+cu118
LMDeploy: 0.5.2.post1+
transformers: 4.43.2
gradio: 4.39.0
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.1.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     0-31,64-95      0               N/A
GPU1    SYS      X      SYS     SYS     0-31,64-95      0               N/A
GPU2    SYS     SYS      X      PIX     32-63,96-127    1               N/A
GPU3    SYS     SYS     PIX      X      32-63,96-127    1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMAnode
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by thiner** [comment]
I repacked existing v0.5.2 image by add an extra line`pip3 install https://mirror.ghproxy.com/https://github.com/irexyc/lmdeploy/releases/download/v0.0.4/lmdeploy-0.5.2.post1+cu118-cp38-cp38-manylinux2014_x86_64.whl`

**Comment by lzhangzz** [comment]
We have updated the prebuilt of PR2218 which should have fix the problem.

https://github.com/lzhangzz/lmdeploy/releases/tag/0.5.2.post2

If the problem persists, you may try to set `NCCL_P2P_DIRECT_DISABLE=1` as a temp workaround.

**Comment by thiner** [comment]
> We have updated the prebuilt of PR2218 which should have fixed the problem.
> 
> https://github.com/lzhangzz/lmdeploy/releases/tag/0.5.2.post2
> 
> If the problem persists, you may try to set `NCCL_P2P_DIRECT_DISABLE=1` as a temp workaround.

Verified, now it's working.
