### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by lyc728** [InternLM/lmdeploy#2230]
使用模型minicpmv2.5报错
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: CUBLAS_STATUS_NOT_SUPPORTED /lmdeploy/src/turbomind/utils/cublasMMWrapper.cc:307 

Aborted (core dumped)
但是使用Internvl2正常推理

**Comment by lyc728** [comment]
现在用原生的推理代码也是报错
<img width="478" alt="企业微信截图_17228479611578" src="https://github.com/user-attachments/assets/83d6e84e-b4c4-44d7-94b2-dcf1bafebd98">

**Comment by lvhan028** [comment]
麻烦提供下 lmdeploy check_env 的执行结果和复现代码

**Comment by lyc728** [comment]
sys.platform: linux
Python: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.2+cu121
LMDeploy: 0.5.2.post1+26b0db5
transformers: 4.43.2
gradio: 3.50.2
fastapi: 0.104.1
pydantic: 1.10.13
triton: 2.1.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    0-23,48-71      0               N/A
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    0-23,48-71      0               N/A
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    0-23,48-71      0               N/A
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    0-23,48-71      0               N/A
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    24-47,72-95     1               N/A
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    24-47,72-95     1               N/A
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    24-47,72-95     1               N/A
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      24-47,72-95     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

**Comment by lyc728** [comment]
解决了

**Comment by irexyc** [comment]
@lyc728 怎么解决的

**Comment by lyc728** [comment]
lmdeploy不能组batch推理 不然显存会超，swift是可以的

**Comment by lvhan028** [comment]
lmdeploy 不能组batch？lmdeploy一直都有Continuous batching
请问，你说的组batch具体是指？

**Comment by lyc728** [comment]
pipe = pipeline(model_path, chat_template_config=ChatTemplateConfig('llama3'))
response = pipe((ask, img_path),(ask, img_path)) 如果是两个的话，这样显存会一直增大

**Comment by lvhan028** [comment]
是说循环调用 `response = pipe((ask, img_path),(ask, img_path))`，发现显存一直上涨么？

**Comment by lyc728** [comment]
是的

**Comment by lvhan028** [comment]
@zhulinJulia24 may add this case to the memory-check test sets

**Comment by lyc728** [comment]
每次请求你不要相同，我是每次请求是不同的，我显存到40g就爆了

**Comment by irexyc** [comment]
@lyc728 

你是两卡么？加载完模型剩余多少G显存？

**Comment by lyc728** [comment]
单卡的

**Comment by lyc728** [comment]
还剩余4G

**Comment by lyc728** [comment]
加了这个限制就好了(cache_max_entry_count=0.8)

**Comment by irexyc** [comment]
@lyc728 

这个值不设置的话，默认就是0.8 😂

**Comment by lyc728** [comment]
改成0.4了








 ----------Reply to Message----------
 On Wed, Aug 7, 2024 20:12 PM Chen ***@***.***&gt; wrote:

  

 
@lyc728
 
这个值不设置的话，默认就是0.8 😂

**Comment by irexyc** [comment]
好的，那看下来就是跟刚启动模型后相比，会有一个显存峰值的问题，先关掉这个issue了。
