### ISSUE TITLE
[Bug] v100上lmdeploy 跑awq微调模型出问题

### ISSUE THREAD

**Issue by EvoNexusX** [InternLM/lmdeploy#2505]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

![image](https://github.com/user-attachments/assets/5bec4518-b2a5-4bc6-bd6f-e632cb8d48f6)
本地a6000测试一切正常，配置lmdeploy==0.6.0a0,torch==2.3.1,triton==2.3.1，在v100上跑报如上错。跑的模型是qwen2.5-32b-instruct-awq。

翻历史bug 报告，有个类似的版本，你们提供的帮助是将triton==2.1.0，然而我在v100上重新进行了测试，又报了如下错。
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```
与那位老哥的报错相似，但是从第一行看上去并不是显存不足的问题，我调小了cache_max_entry_count ，依然没用，救救，请问该如何解决。

### Reproduction

1

### Environment

```Shell
1
```

### Error traceback

```Shell
1
```

**Comment by EvoNexusX** [comment]
代码如下

```
  self.TYPE = "lmdeploy"
  backend_config = PytorchEngineConfig(tp=1, adapters=dict(c1=self.LORA_PATH),
                                       cache_max_entry_count=0.2)

  self.LLM = pipeline(model_path=self.MODEL_PATH,backend_config=backend_config,log_level="INFO")
```
```
gen_config = GenerationConfig(top_p=0.95,
                              temperature=0.7,
                              max_new_tokens=16, skip_special_tokens=True)
torch.cuda.empty_cache()
responses = self.LLM(prompts, adapter_name='c1')
```

**Comment by grimoire** [comment]
> RuntimeError: CUDA error: no kernel image is available for execution on the device

Mismatched nvidia driver version and cuda kernel.

Please provide Environment and Error traceback as the issue template suggested.

**Comment by EvoNexusX** [comment]
> > RuntimeError: CUDA error: no kernel image is available for execution on the device
> 
> Mismatched nvidia driver version and cuda kernel.
> 
> Please provide Environment and Error traceback as the issue template suggested.

Thank you, I have solved this problem by resetting pytorch==2.1.0,torchvision==0.16.0,triton==2.1.0, I think it was because of the original conflict between torch and triton.
