### ISSUE TITLE
8*5060ti performance is low

### ISSUE THREAD

**Issue by gengchaogit** [InternLM/lmdeploy#4226]
8*5060ti performance is low

**Comment by gengchaogit** [comment]
<img width="1970" height="1388" alt="Image" src="https://github.com/user-attachments/assets/1e8d247e-1d43-4c51-b0c9-9b8443f6747e" />

**Comment by gengchaogit** [comment]
<img width="1478" height="1678" alt="Image" src="https://github.com/user-attachments/assets/aacc552d-21e4-450d-a595-409548f09a02" />

**Comment by gengchaogit** [comment]
However, when I switched to vllm, prefill performance improved by 3 times and decode performance improved by 5 times.

**Comment by gengchaogit** [comment]
NCCL_P2P_LEVEL=SYS  CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7,8  lmdeploy serve api_server ~/windows/gpt-oss-120b    --server-port 8099     --tp 8     --session-len 512000     --max-batch-size 32  --model-name lmdeploy     --log-level INFO     --enable-prefix-caching

**Comment by gengchaogit** [comment]
Anyone can use my speed test software to perform the above test. The address is [https://github.com/gengchaogit/llm_speedtest](url)

**Comment by gengchaogit** [comment]
<img width="1522" height="1164" alt="Image" src="https://github.com/user-attachments/assets/39a37d8a-5bb1-4078-9298-686a04b08c31" />

<img width="1506" height="1642" alt="Image" src="https://github.com/user-attachments/assets/10e11a1b-1988-4ea3-80f8-5dbd4743a67e" />

**Comment by gengchaogit** [comment]
My friends are getting good performance with the 5090 and RTX Pro 6000 in a dual-GPU setup with lmdeploy, so I don't understand why the 8-card 5060ti setup is performing so poorly.

**Comment by gengchaogit** [comment]
Does lmdeploy have any specific commands or features tailored for the 50 series graphics cards?

**Comment by Leechy-Litchi** [comment]
Have you tried tp4? I met this problem too. But in my situation, only decode speed is reduced comparing to tp4. (Test Qwen3-30B-A3B on 8*V100)

**Comment by bash99** [comment]
> Have you tried tp4? I met this problem too. But in my situation, only decode speed is reduced comparing to tp4. (Test Qwen3-30B-A3B on 8*V100)

Does you have nvlink between your V100?

BTW, I use lmdeploy to serve Qwen3-30B-A3B-FP8 on 4090 48G, --tp 2 on 2 GPU is slower than --tp 1 on single GPU, about 1500 total token/s vs 2000 total token/s.

So I wonder is there any hide settings I need to touch.

**Comment by Leechy-Litchi** [comment]
> > Have you tried tp4? I met this problem too. But in my situation, only decode speed is reduced comparing to tp4. (Test Qwen3-30B-A3B on 8*V100)
> 
> Does you have nvlink between your V100?
> 
> BTW, I use lmdeploy to serve Qwen3-30B-A3B-FP8 on 4090 48G, --tp 2 on 2 GPU is slower than --tp 1 on single GPU, about 1500 total token/s vs 2000 total token/s.
> 
> So I wonder is there any hide settings I need to touch.

Yes and i think it matters a lot. I've checked latency p2pBandwidthLatencyTest (see https://github.com/NVIDIA/cuda-samples/blob/master/Samples/5_Domain_Specific/p2pBandwidthLatencyTest).  If you cannot use p2p, the latency is 10x higher than nvlink.  You can try this patched driver to enabled it.(https://github.com/aikitoria/open-gpu-kernel-modules/tree/580.105.08-p2p)
latency:
18us->without p2p
2.5us->with p2p
1.8-2us->nvlink
2us-2.1us->PIX(Use P2P when GPUs are on the same PCI switch)
The server is owned by my friend, and he used a pcie swith to connect two 4*V100 adaptor board with 300G nvlink, and i'm still testing whether the PIX bandwitdh limits the speed, but vllm didn't reduce decode speed.

Followings are my results:
Qwen3-30B-A3B-AWQ
2*V100 nvlink
Input Tokens: 971
Output Tokens: 512

| Concurrency | Generation Throughput (tokens/s) |  Prompt Throughput (tokens/s) | Min TTFT (s) | Max TTFT (s) | Success Rate |
|-------------|----------------------------------|-------------------------------|--------------|--------------|--------------|
|           1 |                            78.46 |                      12006.89 |         0.32 |         0.32 |      100.00% |
|           2 |                           133.80 |                      12457.22 |         0.31 |         0.62 |      100.00% |
|           4 |                           238.33 |                      13088.67 |         0.31 |         1.16 |      100.00% |
|           8 |                           390.56 |                      13383.86 |         0.32 |         2.29 |      100.00% |
|          16 |                           569.92 |                      13539.58 |         0.31 |         4.50 |      100.00% |
|          32 |                           706.09 |                      13488.43 |         0.31 |         9.07 |      100.00% |
|          64 |                           809.65 |                      13395.41 |         0.32 |        18.28 |      100.00% |


Qwen3-30B-A3B-AWQ
4*V100 nvlink
Input Tokens: 975
Output Tokens: 512
| Concurrency | Generation Throughput (tokens/s) |  Prompt Throughput (tokens/s) | Min TTFT (s) | Max TTFT (s) | Success Rate |
|-------------|----------------------------------|-------------------------------|--------------|--------------|--------------|
|           1 |                            73.99 |                      16930.43 |         0.23 |         0.23 |      100.00% |
|           2 |                           143.77 |                      18712.20 |         0.22 |         0.41 |      100.00% |
|           4 |                           265.97 |                      19912.99 |         0.22 |         0.77 |      100.00% |
|           8 |                           473.92 |                      20590.60 |         0.21 |         1.49 |      100.00% |
|          16 |                           749.80 |                      21013.36 |         0.21 |         2.92 |      100.00% |
|          32 |                           934.44 |                      21074.10 |         0.26 |         5.83 |      100.00% |
|          64 |                          1182.80 |                      21016.72 |         0.23 |        11.66 |      100.00% |
|         128 |                          1370.24 |                      20761.69 |         0.23 |        23.57 |      100.00% |

I haven't fully tested 8*V100 case, but decode speed in 1 concurrency is 28.33, vllm tp8 is 41.38(40 in tp4).

**Comment by bash99** [comment]
> Yes and i think it matters a lot. I've checked latency p2pBandwidthLatencyTest (see https://github.com/NVIDIA/cuda-samples/blob/master/Samples/5_Domain_Specific/p2pBandwidthLatencyTest). If you cannot use p2p, the latency is 10x higher than nvlink. You can try this patched driver to enabled it.(https://github.com/aikitoria/open-gpu-kernel-modules/tree/580.105.08-p2p) latency: 18us->without p2p 2.5us->with p2p 1.8-2us->nvlink 2us-2.1us->PIX(Use P2P when GPUs are on the same PCI switch) The server is owned by my friend, and he used a pcie swith to connect two 4*V100 adaptor board with 300G nvlink, and i'm still testing whether the PIX bandwitdh limits the speed, but vllm didn't reduce decode speed.
> 

Yes, it works for me, although p2p check latency don't changed so much, but lmdeploy performance vastly improved, at least slighter fast than 1 GPU.

My p2pBandwidthLatencyTest result:
```
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)                                                            [16/36]
   D\D     0      1      2
     0 940.13  20.35  20.56
     1  20.52 949.85  20.40
     2  20.31  20.86 948.68
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1      2
     0 942.40  20.36  20.56
     1  20.43 951.08  20.44
     2  20.20  20.82 951.64
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 945.82  21.71  22.00
     1  21.59 950.40  21.77
     2  21.44  21.86 950.71
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 945.84  21.67  21.99
     1  21.61 950.62  21.73
     2  21.46  21.90 950.43
P2P=Disabled Latency Matrix (us)
   GPU     0      1      2
     0   1.40  14.96  11.74
     1  13.63   1.39  13.17
     2  14.62  14.99   1.36

   CPU     0      1      2
     0   2.59   7.85   7.62
     1   8.16   2.28   7.07
     2   7.97   7.15   2.27
P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1      2
     0   1.38  11.34  11.35
     1  14.86   1.37  13.71
     2  13.89  14.71   1.36

   CPU     0      1      2
     0   2.60   7.89   7.56
     1   8.08   2.26   7.06
     2   7.86   7.12   2.24
```

But tps improve a lot:
Concurrency  Decode(tps) Total(tps)
before:
64	              1258.67        1546.78
after:
64                  2069.34         2543.00

And single GPU(-tp 1) performance:
64	             1640.28          2015.74


The only problem I've is 580 driver has some problem with unsloth 25.09 version, I'll got CUDA oom when merge a lora to full model, 575's driver is ok.

**Comment by gengchaogit** [comment]
actually, my p2p latency result is very good and only have 0.37~0.4us, so it's not p2p issue.

And you can see in vllm I have good performance than lmdeploy.

**Comment by gengchaogit** [comment]
> > > 你试过 TP4 吗？我也遇到过这个问题。不过我的情况是，解码速度比 TP4 慢。（在 8*V100 上测试 Qwen3-30B-A3B）
> > 
> > 
> > 你的V100之间有NVLink连接吗？
> > 顺便说一下，我使用 lmdeploy 在 4090 48G 上部署 Qwen3-30B-A3B-FP8，在 2 个 GPU 上使用 --tp 2 比在单个 GPU 上使用 --tp 1 慢，大约 1500 个令牌/秒 vs 2000 个令牌/秒。
> > 所以我想知道是否有什么隐藏设置需要我去调整。
> 
> 是的，我认为这非常重要。我测试了 p2pBandwidthLatencyTest 的延迟（参见https://github.com/NVIDIA/cuda-samples/blob/master/Samples/5_Domain_Specific/p2pBandwidthLatencyTest）。如果不能使用 p2p，延迟会比 nvlink 高 10 倍。您可以尝试使用这个打过补丁的驱动程序来启用它。( https://github.com/aikitoria/open-gpu-kernel-modules/tree/580.105.08-p2p ) 延迟： 18微秒->不使用P2P ；2.5 微秒->使用P2P ；1.8-2微秒- >NVLink； 2-2.1微秒->PIX（当GPU位于同一PCI交换机上时使用P2P）。 服务器是我朋友的，他使用一个PCIe交换机连接了两块4*V100适配器板，并搭配300G NVLink。我仍在测试PIX带宽是否会限制速度，但VLLM并没有降低解码速度。
> 
> 以下是我的结果： Qwen3-30B-A3B-AWQ 2*V100 nvlink 输入令牌：971 输出令牌：512
> 
> 并发性	生成吞吐量（令牌/秒）	提示吞吐量（令牌/秒）	最小 TTFT（秒）	最大 TTFT（秒）	成功率
> 1	78.46	12006.89	0.32	0.32	100.00%
> 2	133.80	12457.22	0.31	0.62	100.00%
> 4	238.33	13088.67	0.31	1.16	100.00%
> 8	390.56	13383.86	0.32	2.29	100.00%
> 16	569.92	13539.58	0.31	4.50	100.00%
> 32	706.09	13488.43	0.31	9.07	100.00%
> 64	809.65	13395.41	0.32	18.28	100.00%
> Qwen3-30B-A3B-AWQ 4*V100 nvlink 输入令牌：975 输出令牌：512
> 
> 并发性	生成吞吐量（令牌/秒）	提示吞吐量（令牌/秒）	最小 TTFT（秒）	最大 TTFT（秒）	成功率
> 1	73.99	16930.43	0.23	0.23	100.00%
> 2	143.77	18712.20	0.22	0.41	100.00%
> 4	265.97	19912.99	0.22	0.77	100.00%
> 8	473.92	20590.60	0.21	1.49	100.00%
> 16	749.80	21013.36	0.21	2.92	100.00%
> 32	934.44	21074.10	0.26	5.83	100.00%
> 64	1182.80	21016.72	0.23	11.66	100.00%
> 128	1370.24	20761.69	0.23	23.57	100.00%
> 我还没有完全测试 8*V100 的情况，但在 1 个并发情况下解码速度为 28.33，vllm tp8 为 41.38（tp4 为 40）。

(base) root@epyc:~/cuda-samples/Samples/5_Domain_Specific/p2pBandwidthLatencyTest/build# ./p2pBandwidthLatencyTest
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, NVIDIA GeForce RTX 5090, pciBusID: e1, pciDeviceID: 0, pciDomainID:0
Device: 1, NVIDIA GeForce RTX 5060 Ti, pciBusID: 1, pciDeviceID: 0, pciDomainID:0
Device: 2, NVIDIA GeForce RTX 5060 Ti, pciBusID: 2, pciDeviceID: 0, pciDomainID:0
Device: 3, NVIDIA GeForce RTX 5060 Ti, pciBusID: 41, pciDeviceID: 0, pciDomainID:0
Device: 4, NVIDIA GeForce RTX 5060 Ti, pciBusID: 42, pciDeviceID: 0, pciDomainID:0
Device: 5, NVIDIA GeForce RTX 5060 Ti, pciBusID: 81, pciDeviceID: 0, pciDomainID:0
Device: 6, NVIDIA GeForce RTX 5060 Ti, pciBusID: 82, pciDeviceID: 0, pciDomainID:0
Device: 7, NVIDIA GeForce RTX 5060 Ti, pciBusID: a1, pciDeviceID: 0, pciDomainID:0
Device: 8, NVIDIA GeForce RTX 5060 Ti, pciBusID: a2, pciDeviceID: 0, pciDomainID:0
Device=0 CANNOT Access Peer Device=1
Device=0 CANNOT Access Peer Device=2
Device=0 CANNOT Access Peer Device=3
Device=0 CANNOT Access Peer Device=4
Device=0 CANNOT Access Peer Device=5
Device=0 CANNOT Access Peer Device=6
Device=0 CANNOT Access Peer Device=7
Device=0 CANNOT Access Peer Device=8
Device=1 CANNOT Access Peer Device=0
Device=1 CAN Access Peer Device=2
Device=1 CAN Access Peer Device=3
Device=1 CAN Access Peer Device=4
Device=1 CAN Access Peer Device=5
Device=1 CAN Access Peer Device=6
Device=1 CAN Access Peer Device=7
Device=1 CAN Access Peer Device=8
Device=2 CANNOT Access Peer Device=0
Device=2 CAN Access Peer Device=1
Device=2 CAN Access Peer Device=3
Device=2 CAN Access Peer Device=4
Device=2 CAN Access Peer Device=5
Device=2 CAN Access Peer Device=6
Device=2 CAN Access Peer Device=7
Device=2 CAN Access Peer Device=8
Device=3 CANNOT Access Peer Device=0
Device=3 CAN Access Peer Device=1
Device=3 CAN Access Peer Device=2
Device=3 CAN Access Peer Device=4
Device=3 CAN Access Peer Device=5
Device=3 CAN Access Peer Device=6
Device=3 CAN Access Peer Device=7
Device=3 CAN Access Peer Device=8
Device=4 CANNOT Access Peer Device=0
Device=4 CAN Access Peer Device=1
Device=4 CAN Access Peer Device=2
Device=4 CAN Access Peer Device=3
Device=4 CAN Access Peer Device=5
Device=4 CAN Access Peer Device=6
Device=4 CAN Access Peer Device=7
Device=4 CAN Access Peer Device=8
Device=5 CANNOT Access Peer Device=0
Device=5 CAN Access Peer Device=1
Device=5 CAN Access Peer Device=2
Device=5 CAN Access Peer Device=3
Device=5 CAN Access Peer Device=4
Device=5 CAN Access Peer Device=6
Device=5 CAN Access Peer Device=7
Device=5 CAN Access Peer Device=8
Device=6 CANNOT Access Peer Device=0
Device=6 CAN Access Peer Device=1
Device=6 CAN Access Peer Device=2
Device=6 CAN Access Peer Device=3
Device=6 CAN Access Peer Device=4
Device=6 CAN Access Peer Device=5
Device=6 CAN Access Peer Device=7
Device=6 CAN Access Peer Device=8
Device=7 CANNOT Access Peer Device=0
Device=7 CAN Access Peer Device=1
Device=7 CAN Access Peer Device=2
Device=7 CAN Access Peer Device=3
Device=7 CAN Access Peer Device=4
Device=7 CAN Access Peer Device=5
Device=7 CAN Access Peer Device=6
Device=7 CAN Access Peer Device=8
Device=8 CANNOT Access Peer Device=0
Device=8 CAN Access Peer Device=1
Device=8 CAN Access Peer Device=2
Device=8 CAN Access Peer Device=3
Device=8 CAN Access Peer Device=4
Device=8 CAN Access Peer Device=5
Device=8 CAN Access Peer Device=6
Device=8 CAN Access Peer Device=7

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2     3     4     5     6     7     8
     0	     1     0     0     0     0     0     0     0     0
     1	     0     1     1     1     1     1     1     1     1
     2	     0     1     1     1     1     1     1     1     1
     3	     0     1     1     1     1     1     1     1     1
     4	     0     1     1     1     1     1     1     1     1
     5	     0     1     1     1     1     1     1     1     1
     6	     0     1     1     1     1     1     1     1     1
     7	     0     1     1     1     1     1     1     1     1
     8	     0     1     1     1     1     1     1     1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2      3      4      5      6      7      8 
     0 819.35  13.22  12.75  12.67   6.17   9.00   9.49  10.66  12.17 
     1  12.99 429.50  12.11  11.93  12.07  12.14   6.36   7.63   8.55 
     2  11.77  11.95 429.50  12.37  12.23  12.33  12.69  12.71  12.62 
     3  12.42   6.80   8.52 430.68  11.21  12.55  12.80  12.77  12.79 
     4  12.36  12.30  12.19  12.07 429.73  12.03  12.07  12.05  11.64 
     5  10.47   4.81   9.55  12.86  13.13 428.79  13.09  13.12  13.12 
     6  12.11  12.09  13.04  13.11  13.09  13.04 415.75  13.05  13.03 
     7  13.08  12.89  12.84  12.90  12.93  12.85  13.04 415.74  13.06 
     8  13.15  13.09  13.07  13.07  13.08  13.07  13.07  13.06 268.55 
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1      2      3      4      5      6      7      8 
     0 1531.91  13.27  13.45  13.43  13.37  13.42  13.43  13.26  13.27 
     1  13.17 430.21  14.32  14.32  14.32  14.32  14.32  14.32  14.32 
     2  13.14  14.32 430.44  14.32  14.32  14.32  14.32  14.32  14.32 
     3  13.13  14.32  14.32 430.92  14.32  14.32  14.32  14.32  14.32 
     4  13.13  14.32  14.32  14.32 429.27  14.32  14.32  14.31  14.32 
     5  13.09  14.31  14.32  14.32  14.32 430.44  14.32  14.32  14.32 
     6  13.10  14.31  14.32  14.32  14.32  14.32 429.73  14.32  14.32 
     7  13.15  14.32  14.32  14.32  14.31  14.32  14.32 430.68  14.32 
     8  13.16  14.32  14.32  14.32  14.31  14.32  14.32  14.32 430.68 
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2      3      4      5      6      7      8 
     0 1529.57  14.23  14.21  14.13  14.15  14.15  14.13  14.21  14.19 
     1  14.47 429.13  14.33  14.19  14.14  14.10  14.17  14.13  14.05 
     2  14.22  14.32 428.43  14.16  14.18  14.13  14.06  14.10  14.12 
     3  14.46  14.20  14.18 428.07  14.31  14.40  14.43  14.43  14.50 
     4  14.42  14.27  14.13  14.35 428.90  14.28  14.25  14.23  14.23 
     5  14.43  14.26  14.23  14.12  14.05 428.96  14.31  14.24  14.37 
     6  14.34  13.11  11.11  11.91  12.89  13.17 428.31  11.65  10.83 
     7  11.38  12.48  12.57  13.60  13.92  14.21  14.25 428.00  14.62 
     8  14.75  14.49  14.40  14.32  14.31  14.30  14.33  14.63 428.78 
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1      2      3      4      5      6      7      8 
     0 1528.82  14.47  14.44  14.42  14.42  14.43  14.37  14.46  14.45 
     1  14.72 427.49  28.30  28.30  28.31  28.31  28.30  28.31  28.31 
     2  14.70  28.30 427.38  28.30  28.30  28.30  28.30  28.30  28.30 
     3  14.78  28.30  28.30 426.44  28.30  28.30  28.30  28.30  28.30 
     4  14.76  28.30  28.30  28.29 427.61  28.30  28.30  28.30  28.30 
     5  14.75  28.30  28.30  28.30  28.30 427.61  28.30  28.30  28.31 
     6  14.77  28.30  28.30  28.30  28.30  28.30 427.37  28.30  28.30 
     7  14.70  28.30  28.30  28.30  28.30  28.30  28.30 426.91  28.29 
     8  14.76  28.30  28.31  28.31  28.31  28.31  28.31  28.30 428.19 
P2P=Disabled Latency Matrix (us)
   GPU     0      1      2      3      4      5      6      7      8 
     0   2.07  14.33  14.39  14.32  14.31  14.34  14.34  14.37  14.47 
     1  14.33   2.09  14.35  14.32  14.35  14.34  14.31  14.36  14.32 
     2  14.34  14.35   2.09  14.36  14.33  14.33  14.38  14.34  14.31 
     3  14.34  14.32  14.35   2.09  14.37  14.32  14.37  14.34  14.33 
     4  14.34  14.31  14.35  14.34   2.07  14.35  14.33  14.35  14.34 
     5  14.33  14.33  14.32  14.33  14.34   2.09  14.33  14.31  14.31 
     6  14.33  14.35  14.36  14.33  14.35  14.34   2.08  14.36  14.32 
     7  14.32  14.32  14.31  14.34  14.32  14.35  14.33   2.08  14.33 
     8  14.35  14.36  14.33  14.35  14.32  14.38  14.35  14.35   2.08 

   CPU     0      1      2      3      4      5      6      7      8 
     0   2.67   7.40   7.24   7.19   7.15   7.98   8.10   7.79   7.89 
     1   7.87   2.35   6.79   6.78   6.69   7.51   7.44   7.37   7.19 
     2   7.79   6.97   2.32   6.63   6.60   7.38   7.45   7.21   7.45 
     3   7.72   6.65   6.57   2.31   6.67   7.41   7.37   7.35   7.21 
     4   7.71   6.55   6.60   6.53   2.35   7.41   7.54   7.18   7.18 
     5   8.07   7.11   7.06   7.23   7.08   2.67   7.99   7.76   7.76 
     6   8.10   7.05   7.18   7.05   7.11   7.91   2.58   7.97   7.84 
     7   8.00   7.07   7.00   7.12   7.00   7.84   8.09   2.55   7.71 
     8   7.90   6.96   7.15   6.99   7.06   7.80   7.84   7.74   2.54 
**P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1      2      3      4      5      6      7      8 
     0   2.07  14.33  14.34  14.33  14.32  14.34  14.33  14.33  14.34 
     1  14.33   2.09   0.45   0.45   0.45   0.45   0.38   0.38   0.38 
     2  14.34   0.38   2.09   0.46   0.39   0.39   0.38   0.45   0.38 
     3  14.33   0.45   0.39   2.07   0.40   0.39   0.39   0.40   0.44 
     4  14.31   0.38   0.39   0.39   2.09   0.39   0.45   0.39   0.46 
     5  14.33   0.38   0.46   0.46   0.39   2.08   0.39   0.39   0.38 
     6  14.33   0.38   0.46   0.39   0.39   0.39   2.08   0.46   0.38 
     7  14.33   0.38   0.39   0.40   0.40   0.40   0.39   2.08   0.46 
     8  14.32   0.47   0.48   0.40   0.47   0.40   0.48   0.40   2.08** 

   CPU     0      1      2      3      4      5      6      7      8 
     0   2.66   7.29   7.17   7.29   7.11   7.88   7.92   7.83   7.88 
     1   7.60   2.34   1.75   1.80   1.78   1.79   1.81   1.83   1.79 
     2   7.66   1.83   2.39   1.81   1.82   1.92   1.83   1.80   1.88 
     3   7.59   1.81   1.82   2.39   1.80   1.80   1.81   1.81   1.81 
     4   7.60   1.81   1.80   1.79   2.40   1.80   1.81   1.92   1.83 
     5   8.15   2.19   2.09   2.10   2.18   2.68   2.15   2.09   2.09 
     6   8.06   2.11   2.09   2.10   2.09   2.09   2.64   2.15   2.11 
     7   8.01   2.06   2.07   2.08   2.28   2.05   2.07   2.63   2.06 
     8   7.98   2.21   2.06   2.19   2.07   2.07   2.07   2.06   2.58 

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
(base) root@epyc:~/cuda-samples/Samples/5_Domain_Specific/p2pBandwidthLatencyTest/build#

**Comment by lzhangzz** [comment]
@gengchaogit Sorrry for the late reply. We have not verify lmdeploy on a system like yours. There are a few things you can try to help us to get a better understanding of what's going on under the hood.

- The result of `nvidia-smi topo -m`
- Try to serve with `--communicator cuda-ipc`, it may perform better on systems with full-mesh P2P support

btw your result of P2P latency test does not make much sense. I shows that you have inter-GPU write latency lower than the latency of writing a GPU's own memory, which is impratical.

**Comment by gengchaogit** [comment]
> [@gengchaogit](https://github.com/gengchaogit) Sorrry for the late reply. We have not verify lmdeploy on a system like yours. There are a few things you can try to help us to get a better understanding of what's going on under the hood.
> 
> * The result of `nvidia-smi topo -m`
> * Try to serve with `--communicator cuda-ipc`, it may perform better on systems with full-mesh P2P support
> 
> btw your result of P2P latency test does not make much sense. I shows that you have inter-GPU write latency lower than the latency of writing a GPU's own memory, which is impratical.

(base) root@epyc:/# nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	GPU8	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PHB	NODE	NODE	NODE	NODE	NODE	NODE	NODE	0-63	0		N/A
GPU1	PHB	 X 	NODE	NODE	NODE	NODE	NODE	NODE	NODE	0-63	0		N/A
GPU2	NODE	NODE	 X 	PHB	NODE	NODE	NODE	NODE	NODE	0-63	0		N/A
GPU3	NODE	NODE	PHB	 X 	NODE	NODE	NODE	NODE	NODE	0-63	0		N/A
GPU4	NODE	NODE	NODE	NODE	 X 	PHB	NODE	NODE	NODE	0-63	0		N/A
GPU5	NODE	NODE	NODE	NODE	PHB	 X 	NODE	NODE	NODE	0-63	0		N/A
GPU6	NODE	NODE	NODE	NODE	NODE	NODE	 X 	PHB	NODE	0-63	0		N/A
GPU7	NODE	NODE	NODE	NODE	NODE	NODE	PHB	 X 	NODE	0-63	0		N/A
GPU8	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	 X 	0-63	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
(base) root@epyc:/# 


Thank!

But all 50 series GPU P2P Latency is 0.4us. such as rtx pro 6000 and 5090

**Comment by gengchaogit** [comment]
> * --communicator cuda-ipc

will try --communicator cuda-ipc in lmdeploy

**Comment by gengchaogit** [comment]
> > * --communicator cuda-ipc
> 
> will try --communicator cuda-ipc in lmdeploy

not work, same speed
