### ISSUE TITLE
[Bug] qwen-14b进行AWQ + KV Cache之后推理异常

### ISSUE THREAD

**Issue by liuchenyang33** [InternLM/lmdeploy#698]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

------------------------------- server ---------------------------------------------
[WARNING] gemm_config.in is not found; using default GEMM algo
[TM][ERROR] use_context_fmha not support int8
INFO:     Started server process [13913]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: an illegal memory access was encountered /lmdeploy/src/turbomind/models/llama/LlamaBatch.cc:876 

Aborted

--------------------------------------------------- chat -------------------------------------------------
(LargeModel) appuser@alpha87:/mnt3/lcy/workspaces/llm_models$ lmdeploy chat turbomind workspace-qwen14b-awq/
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 138, in _create_weight
    model_comm.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32 

[WARNING] gemm_config.in is not found; using default GEMM algo
Exception in thread Thread-2:
Traceback (most recent call last):
(LargeModel) appuser@alpha87:/mnt3/lcy/workspaces/llm_models$ lmdeploy chat turbomind workspace-qwen14b-awq/
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 138, in _create_weight
    model_comm.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32 

[WARNING] gemm_config.in is not found; using default GEMM algo
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 202, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:231 

session 1

double enter to end input >>> j

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
j<|im_end|>
<|im_start|>assistant
 Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/LargeModel/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/cli/chat.py", line 85, in turbomind
    run_turbomind_model(model_path,
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/turbomind/chat.py", line 137, in main
    for outputs in generator.stream_infer(
  File "/home/appuser/miniconda3/envs/LargeModel/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 268, in stream_infer
    self.model_insts[0].register_callback(self._forward_callback)
AttributeError: 'NoneType' object has no attribute 'register_callback'

### Reproduction

# 生成量化参数
lmdeploy lite calibrate \
  --model Qwen-14B-Chat \
  --calib_dataset 'c4' \
  --calib_samples 128 \
  --calib_seqlen 2048 \
  --work_dir  lmdeploy-qwen14-awq
  
# 量化成int4
lmdeploy lite auto_awq \
  --model Qwen-14B-Chat\
  --w_bits 4 \
  --w_group_size 128 \
  --work_dir  lmdeploy-qwen14-awq
  
# AWQ量化
lmdeploy convert --model-name qwen-14b     --model-path ./lmdeploy-qwen14-awq    --model-format awq     --group-size 128

# KV Cache
lmdeploy lite kv_qparams --work_dir lmdeploy-qwen14-awq --turbomind_dir workspace-qwen14b-awq/triton_models/weights/ --kv_sym False --num_tp 1

# 模型推理
lmdeploy chat turbomind ./workspace

# 模型服务部署
CUDA_VISIBLE_DEVICES=2 lmdeploy serve api_server ./workspace-qwen14b-awq/ --instance_num 32 --tp 1

### Environment

```Shell
pip install lmdeploy
```

**Comment by irexyc** [comment]
> model_comm.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32

什么显卡？log看起来模型加载就失败了，显存不够

**Comment by liuchenyang33** [comment]
A30显卡正常部署14B-AWQ模型占用12G显存，最新的master编译完已解决，
