### ISSUE TITLE
[Bug] support cuda version 11.4

### ISSUE THREAD

**Issue by hxtkyne** [InternLM/lmdeploy#708]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Thank you for your awesome works.
I have test successfully when my cuda driver version is cuda-11.7（nvidia-smi command）, but fail for cuda-11.4. Do you have any suggestions？In fact, i cannot simply upgrade my cuda driver for some reasons.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 202, in _create_model_instance
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 202, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: API call is not supported in the installed CUDA driver /lmdeploy/src/turbomind/utils/allocator.h:169 

### Reproduction

run for qwen-7b/14b model.

### Environment

```Shell
lmdeploy check_env:

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A10
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (GCC) 9.2.1
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu117
LMDeploy: 0.0.14+
transformers: 4.33.0
gradio: 3.50.2
fastapi: 0.104.1
pydantic: 1.9.2






nvidia-smi:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A10-1-PCIE-24GB...  On   | 00000000:6B:00.0 Off |                    0 |
|  0%   31C    P8    21W / 150W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A10-1-PCIE-24GB...  On   | 00000000:E3:00.0 Off |                    0 |
|  0%   33C    P8    22W / 150W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

**Comment by lzhangzz** [comment]
This is strange, the stream-ordered allocator API was introduced in CUDA 11.2, should be OK uisng CUDA 11.4. 

I guess the problem is that you are using CUDA 11.7 runtime while the driver only supports up to CUDA 11.4.

**Comment by hxtkyne** [comment]
邮件已收到了哦亲，经常联系啊。好朋友走一生

**Comment by hxtkyne** [comment]
> This is strange, the stream-ordered allocator API was introduced in CUDA 11.2, should be OK using CUDA 11.4.
> 
> I guess the problem is that you are using CUDA 11.7 runtime while the driver only supports up to CUDA 11.4.

I have downgrade CUDA 11.7 runtime to CUDA 11.4, it still raise an error. The error function line is in:

**Comment by hxtkyne** [comment]
I have tested different cuda versions, but still not work. Do you have tested on different versions like cuda11.4?

**Comment by lvhan028** [comment]
Hi, @hxtkyne
CUDA in our server is " NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7"
We have no authority to change the driver.
I am trying to find another device to reproduce it.

**Comment by lvhan028** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/4560679/c4008303-94b4-4c28-9d1f-910c62576315)

**Comment by lvhan028** [comment]
@hxtkyne 
Can you try lmdeploy prebuilt package and check if it works on cuda 11.4?

**Comment by hxtkyne** [comment]
Really Thanks for your all reply, I solved it .
